### ISSUE TITLE
Pdf files are not shown in Firefox

### ISSUE THREAD

**Issue by restless** [dealfonso/pdfjs-viewer#12]
I'm using latest Firefox 126.01 (Ubuntu) and the pdfjs-viewer doesn't show pdf files at all.

I can reproduce it with all codepen examples.

For instance: https://codepen.io/dealfonso/pen/qBPPEEd is rendered as:

![Firefox-PDFjs-viewer (example 2)](https://github.com/dealfonso/pdfjs-viewer/assets/90477/9f4aefd9-52e4-4e2f-9d9e-9a99aa948788)

No errors are printed in the console, also there are no network errors. Happens also in the incognito mode with all adblockers etc being turned off. At the same time all is good in other browsers like Vivaldi.

**Comment by dealfonso** [comment]
Hi,
That's weird because I have just downloaded Firefox for MacOS, and it works as expected... I do not have any Linux to try, but I'll manage to get one in the future and let you know.

**Comment by restless** [comment]
@dealfonso thank you for taking a look. I nailed this down to be an issue with my browser and nvidia drivers or something else. Anyway, not pdfjs-viewer specific so I'm closing this issue.
