### ISSUE TITLE
Clicking on thumbnail does not update page in example.html

### ISSUE THREAD

**Issue by holdenhao** [dealfonso/pdfjs-viewer#15]
It only works after clicking any of the rotate buttons.  There are no errors reported on the browser console.

**Comment by dealfonso** [comment]
hi,
yes, it is a bug of the example.html file. It is corrected on branch _nojquery_ and will be merged in the main branch soon

**Comment by dealfonso** [comment]
hi,
I have just released a new version of the library. The bug is corrected in this version.

**Comment by holdenhao** [comment]
Thank you!  I updated my copy and did some tests.  I confirm the fix.
