### ISSUE TITLE
The viewfinder image is distorted.

### ISSUE THREAD

**Issue by MaGaC** [dealfonso/pdfjs-viewer#2]
How to make the viewer not distort the image when you have several pages with different dimensions.

Thanks for your help.

![Sin título](https://user-images.githubusercontent.com/65728236/183769308-188bd787-0d41-4cc2-84e3-f19635a6d330.png)

**Comment by dealfonso** [comment]
Hi,
could you please provide an example PDF file?

**Comment by dealfonso** [comment]
Closed due to inactivity

**Comment by dealfonso** [comment]
This problem has been solved in latest release 1.1.1
