### ISSUE TITLE
Loading PDF as URL

### ISSUE THREAD

**Issue by oleteacher** [dealfonso/pdfjs-viewer#3]
Nice work!

I am wondering if it is possible to open PDF's using the name in a URL. For example:

example.com/pdfjs-viewer/index.php?pdffile=somedoc.pdf

Need something like your pdfjs-viewer to use on school network to open local PDF's and restrict downloading them.

Thanks for sharing.

**Comment by dealfonso** [comment]
Hi,

I have updated the example.html example to include this kind of use case :) Please check commit 3a63c1eecf2723094006beeabf77f5b0dfbb3bb3

**Comment by oleteacher** [comment]
Sorry for no reply, life got in the way:)

Thank you much for your work!
