### ISSUE TITLE
Print feature

### ISSUE THREAD

**Issue by UsmanFarooq-Dev** [dealfonso/pdfjs-viewer#8]
Thanks for creating this simple and easy to use library.

The original pdf.js library has print feature.

![image](https://github.com/dealfonso/pdfjs-viewer/assets/46762281/7ee74d00-7617-48df-bb69-0ad13d2f2833)

Is there any possibility to include this feature in this library?

**Comment by dealfonso** [comment]
Hi,

You can use the `print-js` library (https://printjs.crabbly.com/), as it enables to easily print a pdf file `printJS('docs/printjs.pdf')`. The next code is a working example for this `pdfjs-viewer` library:

```javascript
// Create the viewer
let pdfViewer = new PDFjsViewer($('.pdfjs-viewer'));

// Load the PDF document
await pdfViewer.loadDocument("test.pdf");

// ... do things with the document

// Print the data
let pdfData = await pdfViewer.pdf.getData();
let b64Pdf=btoa(String.fromCharCode.apply(null, pdfData));
printJS({printable: b64Pdf, type: 'pdf', base64: true});
```

Regards.

**Comment by UsmanFarooq-Dev** [comment]
Awesome, thank you!

Just a little thing.

I was getting "Maximum call stack size exceeded" error while converting `pdfData` to base64 string on second last line of your code.

To fix this, just replace

`let b64Pdf=btoa(String.fromCharCode.apply(null, pdfData));`
 
With

```
let uint8Array = new Uint8Array(pdfData);
let CHUNK_SIZE = 0x8000; // Arbitrary chunk size, adjust as needed

let chunks = [];
for (let i = 0; i < uint8Array.length; i += CHUNK_SIZE) {
    chunks.push(uint8Array.subarray(i, i + CHUNK_SIZE));
}

let blob = new Blob(chunks, { type: 'application/pdf' });
let b64Pdf = await new Promise((resolve) => {
    let reader = new FileReader();
    reader.onloadend = function () {
        resolve(reader.result.split(',')[1]);
    };
    reader.readAsDataURL(blob);
});
```

Regards
Usma Farooq

**Comment by dealfonso** [comment]
Hi, 
yes, I just wanted to make it easy for the example.
Thank you for the full example. I will include in the new examples.
Regards.
